spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC
    hikari:
      username: root
      password: wzp
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #指定namespace
        #namespace: 4477b935-9f77-418e-b217-e1803cefbb01
        #指定集群名称
        cluster-name: HRB
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          #group一定要设置(如果使用的是其他的mq，可留空)
          group: binder-group
  application:
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      #默认是0.1(只抽样百分之10的数据)
      probability: 1.0
server:
  port: 8081
logging:
  level:
    com.alibaba.nacos: error
jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
